Add logging for partner publish pipeline

diff --git a/eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml b/eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
--- a/eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
+++ b/eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
@@ -54,9 +54,14 @@ jobs:
           azurePowerShellVersion: LatestVersion 
           pwsh: true
           Inline: |
+            echo "azcopy copy '${{ parameters.PartnerDropsBlobBase }}/${{ parameters.PartnerDropsBlobSourceSuffix }}/*' '${{ parameters.ArtifactsPath }}' --recursive=true"
             azcopy copy '${{ parameters.PartnerDropsBlobBase }}/${{ parameters.PartnerDropsBlobSourceSuffix }}/*' '${{ parameters.ArtifactsPath }}' --recursive=true
-            echo "Copied files:"
-            dir '${{ parameters.ArtifactsPath }}' -r | % { $_.FullName }
+            $copiedFiles = (dir '${{ parameters.ArtifactsPath }}' -r | % { $_.FullName })
+            echo "Copied files: $copiedFiles"
+            if (!$copiedFiles) { 
+              echo "Failed to copy any files from '${{ parameters.PartnerDropsBlobBase }}/${{ parameters.PartnerDropsBlobSourceSuffix }}/*' please double check they exist"
+              exit 1
+            }            
         env: 
           AZCOPY_AUTO_LOGIN_TYPE: 'PSCRED'     
 
