fix-publish

diff --git a/tools/mock-service-host/ci.yml b/tools/mock-service-host/ci.yml
--- a/tools/mock-service-host/ci.yml
+++ b/tools/mock-service-host/ci.yml
@@ -105,7 +105,7 @@ stages:
             for file in $(VAR_BUILD_ARTIFACT_STAGING_DIRECTORY)/$(VAR_ARIFACT_NAME)/*.tgz
             do
               echo -e "\e[32m[$(date -u)] LOG: File: $file"
-              pnpm publish $file --tag latest --access public --no-git-checks || { echo 'publish $file failed' ; exit 1; }
+              npm publish $file --access public || { echo 'publish $file failed' ; exit 1; }
             done
             rm ~/.npmrc || { echo 'rm ~/.npmrc failed' ; exit 1; }
           displayName: Publish
