Update patch application logic

diff --git a/eng/pipelines/templates/steps/sync-directory.yml b/eng/pipelines/templates/steps/sync-directory.yml
--- a/eng/pipelines/templates/steps/sync-directory.yml
+++ b/eng/pipelines/templates/steps/sync-directory.yml
@@ -24,19 +24,22 @@ steps:
           pushd ${{ repo }}
           $results = @()
           echo "##vso[task.setvariable variable=HasChanges]$false"
+          $shaBeforePatches = git rev-parse --short HEAD
+          Write-Host $shaBeforePatches
           foreach ($file in (Get-ChildItem $(PatchFilesLocation)))
           {
-            $results += git -c user.name="azure-sdk" -c user.email="azuresdk@microsoft.com" am $file.FullName
+             Write-Host $file.FullName
+             git -c user.name="azure-sdk" -c user.email="azuresdk@microsoft.com" am -3 $file.FullName
+             if ($lastExitCode -ne 0) { 
+               git am --show-current-patch=diff
+               Write-Error "##vso[task.LogIssue type=warning;]Failed to properly apply patch files to [https://github.com/azure/${{ repo }}]"
+               exit 1
+             }
           }
-          if (($results.Count -eq (Get-ChildItem $(PatchFilesLocation))) -and ($LASTEXITCODE -eq 0))
-          {
-            echo "##vso[task.setvariable variable=HasChanges]$true"
-          }
-          else
-          {
-            Write-Output "Failed to properly apply patch files to [https://github.com/azure/${{ repo }}]"
-            echo "##vso[task.setvariable variable=HasChanges]$false"
-          }
+          $shaAfterPatches = git rev-parse --short HEAD
+          Write-Host $shaAfterPatches
+          $hasChanges = $shaBeforePatches -ne $shaAfterPatches
+          echo "##vso[task.setvariable variable=HasChanges]$hasChanges"
         }
         else
         {
